"""UTF-8 byte tokens, leak-free splits, and deterministic next-token batches."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TypeAlias

import numpy as np
from numpy.typing import NDArray


ByteArray: TypeAlias = NDArray[np.unsignedinteger]
IntegerArray: TypeAlias = NDArray[np.integer]


@dataclass(frozen=True, slots=True)
class ByteCorpusSplit:
    """Contiguous, non-overlapping train and validation token arrays."""

    train: ByteArray
    validation: ByteArray
    split_index: int


@dataclass(frozen=True, slots=True)
class ByteBatch:
    """Input bytes, one-position-shifted targets, and sampled start indices."""

    inputs: IntegerArray
    targets: IntegerArray
    start_indices: IntegerArray


def _positive_integer(value: int, name: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")
    return value


def _byte_tokens(tokens: IntegerArray, name: str) -> IntegerArray:
    values = np.asarray(tokens)
    if values.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")
    if not np.issubdtype(values.dtype, np.integer):
        raise TypeError(f"{name} must contain integers")
    if values.size and (np.min(values) < 0 or np.max(values) > 255):
        raise ValueError(f"{name} values must be in the inclusive range 0..255")
    return values


def encode_utf8(text: str) -> ByteArray:
    """Encode text as writable uint8 tokens from the fixed 256-byte vocabulary."""

    if not isinstance(text, str):
        raise TypeError("text must be a string")
    return np.frombuffer(text.encode("utf-8"), dtype=np.uint8).copy()


def decode_utf8(
    token_ids: IntegerArray,
    *,
    errors: str = "replace",
) -> str:
    """Decode byte IDs; replacement mode keeps arbitrary generated bytes visible."""

    if errors not in {"strict", "replace", "ignore"}:
        raise ValueError("errors must be 'strict', 'replace', or 'ignore'")
    values = _byte_tokens(token_ids, "token_ids")
    return bytes(values.astype(np.uint8, copy=False)).decode(
        "utf-8",
        errors=errors,
    )


def split_byte_tokens(
    token_ids: IntegerArray,
    *,
    validation_fraction: float,
    context_length: int,
) -> ByteCorpusSplit:
    """Create contiguous splits whose training windows cannot enter validation."""

    values = _byte_tokens(token_ids, "token_ids")
    resolved_context_length = _positive_integer(context_length, "context_length")
    if isinstance(validation_fraction, (bool, np.bool_)):
        raise TypeError("validation_fraction must be a real number")
    try:
        resolved_fraction = float(validation_fraction)
    except (TypeError, ValueError) as error:
        raise TypeError("validation_fraction must be a real number") from error
    if not np.isfinite(resolved_fraction) or not 0.0 < resolved_fraction < 1.0:
        raise ValueError("validation_fraction must satisfy 0 < value < 1")

    validation_size = int(np.floor(values.size * resolved_fraction))
    split_index = values.size - validation_size
    minimum_split_size = resolved_context_length + 1
    if split_index < minimum_split_size or validation_size < minimum_split_size:
        raise ValueError(
            "both splits must contain at least context_length + 1 tokens"
        )
    return ByteCorpusSplit(
        train=values[:split_index].astype(np.uint8, copy=True),
        validation=values[split_index:].astype(np.uint8, copy=True),
        split_index=split_index,
    )


def sample_next_token_batch(
    token_ids: IntegerArray,
    *,
    batch_size: int,
    context_length: int,
    rng: np.random.Generator,
) -> ByteBatch:
    """Sample windows with replacement and pair each byte with its successor."""

    values = _byte_tokens(token_ids, "token_ids")
    resolved_batch_size = _positive_integer(batch_size, "batch_size")
    resolved_context_length = _positive_integer(context_length, "context_length")
    if not isinstance(rng, np.random.Generator):
        raise TypeError("rng must be a numpy.random.Generator")
    maximum_start = values.size - resolved_context_length - 1
    if maximum_start < 0:
        raise ValueError("token_ids must contain at least context_length + 1 tokens")

    start_indices = rng.integers(
        0,
        maximum_start + 1,
        size=resolved_batch_size,
        dtype=np.int64,
    )
    offsets = np.arange(resolved_context_length + 1, dtype=np.int64)
    windows = values[start_indices[:, None] + offsets[None, :]]
    return ByteBatch(
        inputs=windows[:, :-1].astype(np.int64, copy=False),
        targets=windows[:, 1:].astype(np.int64, copy=False),
        start_indices=start_indices,
    )
